vich_uploader:
    db_driver: orm
    metadata:
      type: attribute

    mappings:
        image_directory:
            uri_prefix: /public/image/profil
            upload_destination: '%kernel.project_dir%/public/image/profil'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
